import '@/helpers/cookie'

import '@/components/sprite'
import '@/components/share'
import '@/components/order_modal/index'
import '@/components/required'
import '@/components/cookie'
import '@/components/thank-you'

import '@/layout/nav'
import '@/layout/tablet'

import '@/pages/news'
import '@/pages/about'
import '@/pages/gallery'
import '@/pages/buy/index'
import '@/pages/index/index'
import '@/pages/acc'
import '@/pages/support'
import '@/pages/subscribe/index'
